server.port=8084
ollama.base-url=http://host.docker.internal:11434
ollama.model=phi3
ollama.vision-model=llava
ollama.timeout=120000
server.tomcat.max-http-form-content-size=10MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
springdoc.api-docs.path=/v3/api-docs